from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class StepMetrics(BaseModel):
    """Metrics for one LLM generation and sandbox execution cycle."""

    step: int = Field(..., description="1-indexed iteration number")
    input_tokens: int = Field(
        ..., description="Tokens sent to the LLM for this step"
    )
    output_tokens: int = Field(
        ..., description="Tokens generated by the LLM for this step"
    )
    request_time_ms: float = Field(
        ...,
        description="Wall-clock time for the LLM API call in milliseconds",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 timestamp of when this step was recorded",
    )
    api_url: str = Field(
        default="",
        description="Base URL of the LLM API endpoint",
    )
    model_name: str = Field(
        default="",
        description="Model identifier used for this step",
    )
    llm_output: str = Field(
        default="",
        description="Raw text generated by the LLM before code extraction",
    )
    sandbox_input: str = Field(
        default="",
        description="Python code sent to the sandbox for execution",
    )
    sandbox_output: str = Field(
        default="",
        description="Sandbox execution result (stdout/stderr/error message)",
    )
    retries: int = Field(
        default=0,
        description=(
            "Number of LLM API retries before getting a successful response "
            "(0 = first attempt succeeded)"
        ),
    )


class SolutionOutput(BaseModel):
    """Required output format shared by MBPP and SWE-bench agents."""

    task_id: str = Field(
        ...,
        description="Task identifier (MBPP task_id or SWE-bench instance_id)",
    )
    benchmark: str = Field(
        ...,
        description="Benchmark type: 'mbpp' or 'swebench'",
    )
    success: bool = Field(
        ...,
        description="Whether the agent believes it solved the task",
    )
    solution: str = Field(
        ...,
        description="Python code for MBPP or a git patch for SWE-bench",
    )
    iterations: int = Field(
        ...,
        description="Number of agent loop iterations used",
    )
    total_requests: int = Field(
        ...,
        description="Total number of LLM API requests made (including retries)",
    )
    total_input_tokens: int = Field(
        ...,
        description="Sum of input_tokens across all steps",
    )
    total_output_tokens: int = Field(
        ...,
        description="Sum of output_tokens across all steps",
    )
    total_time_seconds: float = Field(
        ...,
        description="Wall-clock time from agent start to finish",
    )
    steps: List[StepMetrics] = Field(
        default_factory=list,
        description="Per-step metrics, one entry per agent iteration",
    )
    system_prompt: str = Field(
        default="",
        description="Full system prompt sent to the LLM (for provenance checking)",
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if the agent failed (None if successful)",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="ISO 8601 timestamp of when the solution was produced",
    )
